version: 2
updates:

  # Maintain dependencies for Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "kind/dependabot"
    reviewers:
      - "k3s-io/k3s-dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/package"
    labels:
      - "kind/dependabot"
    reviewers:
      - "k3s-io/k3s-dev"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "kind/dependabot"
    reviewers:
      - "k3s-io/k3s-dev"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 15
    directory: "/"
    labels:
      - "kind/dependabot"
    reviewers:
      - "k3s-io/k3s-dev"
    schedule:
      interval: "weekly"
    groups:
      etcd-dependencies:
        patterns:
          - go.etcd.io/*
    ignore:
      - dependency-name: "github.com/nats-io/nats-server/v2"
      - dependency-name: "k8s.io/*"
    
    # Maintain dependencies for K8s seperately, with a different schedule
  - package-ecosystem: "gomod"
    target-branch: main # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    open-pull-requests-limit: 1
    directory: "/"
    labels:
      - "kind/dependabot"
    reviewers:
      - "k3s-io/k3s-dev"
    schedule:
      interval: "monthly"
    groups:
      k8s-dependencies:
        patterns:
          - k8s.io/*
    allow:
      - dependency-name: "k8s.io/*"