version: 2
updates:

  # Maintain dependencies for Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "kind/dependabot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/package"
    labels:
      - "kind/dependabot"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "kind/dependabot"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 15
    directory: "/"
    target-branch: "master" # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    labels:
      - "kind/dependabot"
    schedule:
      interval: "weekly"
    groups:
      etcd-dependencies:
        patterns:
          - go.etcd.io/*
    ignore:
      - dependency-name: k8s.io/*
      - dependency-name: "github.com/nats-io/nats-server/v2"

   # Maintain dependencies for K8s monthly
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "kind/dependabot"
    schedule:
      interval: "monthly"
    groups:
      k8s-dependencies:
        patterns:
          - k8s.io/*
    ignore:
      - dependency-name: "*"
