---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker:25.0.5
  commands:
  - apk add make git bash file
  - git config --global --add safe.directory /drone/src
  - make
  environment:
    ARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

- name: test-image
  image: docker:25.0.5
  commands:
  - docker build -t kine:test-${DRONE_COMMIT} -f Dockerfile.test .
  environment:
    ARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

- name: test-sqlite
  image: docker:25.0.5
  depends_on:
   - build
   - test-image
  commands:
  - > 
    docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME
    -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
    --privileged kine:test-${DRONE_COMMIT} "./scripts/test sqlite"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

- name: test-mysql
  image: docker:25.0.5
  depends_on:
   - build
   - test-image
  commands:
  - > 
    docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME
    -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
    --privileged kine:test-${DRONE_COMMIT} "./scripts/test mysql"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

- name: test-postgres
  image: docker:25.0.5
  depends_on:
   - build
   - test-image
  commands:
  - > 
    docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME
    -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
    --privileged kine:test-${DRONE_COMMIT} "./scripts/test postgres"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

- name: test-schema-migration
  image: docker:25.0.5
  depends_on:
   - build
   - test-image
  commands:
  - > 
    docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME
    -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
    --privileged kine:test-${DRONE_COMMIT} "./scripts/test schema-migration"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

- name: test-nats
  image: docker:25.0.5
  depends_on:
   - build
   - test-image
  commands:
  - > 
    docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME
    -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
    --privileged kine:test-${DRONE_COMMIT} "./scripts/test nats"
  - >
    docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME
    -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
    --privileged kine:test-${DRONE_COMMIT} "./scripts/test nats-embedded"
  - >
    docker run -i -e ARCH -e REPO -e TAG  -e DRONE_TAG -e IMAGE_NAME
    -v /var/run/docker.sock:/var/run/docker.sock -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
    --privileged kine:test-${DRONE_COMMIT} "./scripts/test nats-socket"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
