FROM golang:1.21-alpine3.17 AS dapper

ARG ARCH=amd64

RUN apk -U add bash ca-certificates coreutils curl docker-cli file findutils gcc git less musl-dev vim wget
RUN apk -U add py3-pip && pip install kubernetes termplotlib==v0.3.4

ENV DAPPER_RUN_ARGS --privileged -v kine-cache:/go/src/github.com/k3s-io/kine/.cache
ENV DAPPER_ENV ARCH REPO TAG DRONE_TAG IMAGE_NAME CROSS
ENV DAPPER_SOURCE /go/src/github.com/k3s-io/kine/
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["test"]
