FROM golang:1.21-alpine3.17

ARG ARCH=amd64

RUN apk -U add bash ca-certificates coreutils curl docker-cli file findutils gcc git less musl-dev vim wget
RUN apk -U add py3-pip && pip install kubernetes termplotlib==v0.3.4

ENV KINE_SOURCE /go/src/github.com/k3s-io/kine/
ENV HOME ${KINE_SOURCE}
WORKDIR ${KINE_SOURCE}


COPY . ${KINE_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["test"]
