{
 "title": "k3s kine",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "loki_datasource", "query": "loki" },
   { "name": "query", "label": "logs contains string" },
   {
    "name": "query_regexp",
    "label": "logs contains a match to the regular expression"
   }
  ]
 },
 "panels": [
  {
   "title": "Kine Pod bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod network bandwidth",
     "type": "timeseries",
     "description": "container_network_receive_bytes_total cumulative bytes received excluding eth0\nSee https://github.com/google/cadvisor/issues/2615",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(node) (\r\n    sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", interface!=\"eth0\"}[$__rate_interval]))\r\n     + on(pod) group_left(node) sum by(pod, node) (kube_pod_info{namespace=\"$namespace\"})\r\n)",
       "legendFormat": "receive by {{node}}"
      },
      {
       "expr": "sum by (node) (\r\nsum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", interface!=\"eth0\"}[$__rate_interval]))\r\n+ on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"$namespace\"})\r\n  )",
       "legendFormat": "transmit by {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kine Pod bandwidth per node and interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod network bandwidth",
     "type": "timeseries",
     "description": "container_network_receive_bytes_total cumulative bytes received excluding eth0\nSee https://github.com/google/cadvisor/issues/2615",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(node,interface) (\r\n    sum by(pod,interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__rate_interval]))\r\n     + on(pod) group_left(node) sum by(pod, node) (kube_pod_info{namespace=\"$namespace\"})\r\n)",
       "legendFormat": "receive by pod on node={{node}} on if={{interface}}"
      },
      {
       "expr": "sum by (node,interface) (\r\n   sum by(pod,interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__rate_interval]))\r\n    + on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"$namespace\"})\r\n)",
       "legendFormat": "transmit by pod on node={{node}} on if={{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kine debug logs stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by(pod) (count_over_time({namespace=~\"$namespace\"} |= \"$query\" |~ \"$query_regexp\" [$__interval]) )    "
      }
     ]
    }
   ]
  },
  {
   "title": "Kine debug logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "description": "Logs from services running in Kubernetes",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\"} |= \"$query\" |~ \"$query_regexp\""
      }
     ]
    }
   ]
  },
  {
   "title": "SQL connections ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "kine active and max connections",
     "type": "timeseries",
     "description": "The number of established connections both in use and idle.    \ngo_sql_max_open_connections{db_name=\"kine\"}\n\nMaximum number of open connections to the database.\ngo_sql_max_open_connections ",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "sum by (node) (\r\n   sum by(pod) (go_sql_in_use_connections ) \r\n   + on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})\r\n)",
       "legendFormat": "active on pod {{pod}} on node {{node}}"
      },
      {
       "expr": "sum by (node) (\r\n   sum by(pod) (go_sql_max_open_connections  ) \r\n   + on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})\r\n)",
       "legendFormat": "max nb cnx for pod {{pod}} on node {{node}}"
      }
     ]
    },
    {
     "title": "kine sql closed connections per seconds ",
     "type": "timeseries",
     "description": "go_sql_max_idle_closed_total The total number of connections closed due to SetMaxIdleConns.\ngo_sql_max_lifetime_closed_total The total number of connections closed due to SetConnMaxLifetime.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "rate(go_sql_max_idle_closed_total [$__rate_interval])",
       "legendFormat": "max idle on pod {{pod}} "
      },
      {
       "expr": "rate(go_sql_max_idle_time_closed_total [$__rate_interval])",
       "legendFormat": "max lifetime on pod {{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "compaction completion events per pod",
     "type": "timeseries",
     "description": "each dot represents a change in the kine_compact_total metric\nThe metric is updated by kine after the compaction ends, see source at https://github.com/k3s-io/kine/blob/c1da9bfb3f95dc329f7bacdd6f46b6c824d29ec2/pkg/logstructured/sqllog/sql.go#L168",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "compactions par seconds" } },
     "targets": [
      {
       "expr": "sum by (node) (\r\nsum by(pod) (rate(kine_compact_total[$__rate_interval]))\r\n* on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"$namespace\"})\r\n  )\r\n",
       "legendFormat": "pod on node={{node}}"
      }
     ]
    },
    {
     "title": "rate of compactions per node and result",
     "type": "timeseries",
     "description": "number of compactions",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "requests per hour" } },
     "targets": [
      {
       "expr": "sum by (node,result) (\r\n  sum by(pod, result) (rate(kine_compact_total{}[$__rate_interval])) * 3600\r\n  * on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"$namespace\"})\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sql request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "kine sql queries per node",
     "type": "timeseries",
     "description": "number of SQL operations: kine_sql_total",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (node) (\r\n   sum by(pod) (rate(kine_sql_total[$__rate_interval])) \r\n   + on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})\r\n)",
       "legendFormat": "pod {{pod}} on node {{node}}"
      }
     ]
    },
    {
     "title": "kine sql queries per pod ",
     "type": "timeseries",
     "description": "number of SQL operations. Individual pods are listed, potentially multiple ones on a same node",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(kine_sql_total[$__rate_interval])) \r\n+ on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})",
       "legendFormat": "pod {{pod}} on node {{node}}"
      }
     ]
    },
    {
     "title": "Successfull kine requests latency by pod",
     "type": "timeseries",
     "description": " Length of time per SQL operation (in seconds, metric kine_sql_time_seconds  )",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(kine_sql_time_seconds_sum{error_code=\"\"}[$__rate_interval]) / rate(kine_sql_time_seconds_count{error_code=\"\"}[$__rate_interval]))\r\n* on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Layout tweak",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "options": {
      "content": "Just a trick to insert a blank panel and align errors below"
     }
    },
    {
     "title": "Errored kine sql queries per error code",
     "type": "timeseries",
     "description": "number of SQL operations",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(error_code) (rate(kine_sql_total{error_code!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errored kine sql queries per node ",
     "type": "timeseries",
     "description": "number of SQL operations",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(node) (\r\n   sum by(pod) (rate(kine_sql_total{error_code!=\"\"}[$__rate_interval])) \r\n   * on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})\r\n)",
       "legendFormat": "pod {{pod}} on node {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sql request latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sucessfull kine requests latency by node",
     "type": "timeseries",
     "description": " Length of time per SQL operation (in seconds, metric kine_sql_time_seconds  )",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (node) (\r\n sum by (pod) (rate(kine_sql_time_seconds_sum{error_code=\"\"}[$__rate_interval]) / rate    (kine_sql_time_seconds_count        {error_code=\"\"}[$__rate_interval]))\r\n* on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "latency of kine sql queries per error code",
     "type": "timeseries",
     "description": "number of SQL operations",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by(error_code) (rate(kine_sql_time_seconds_sum[$__rate_interval]))) / (sum by(error_code) (rate(kine_sql_time_seconds_count[$__rate_interval])))",
       "legendFormat": "{{error_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go lang metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "kine goroutines ",
     "type": "timeseries",
     "description": "# HELP go_goroutines Number of goroutines that currently exist.                                          \n# TYPE go_goroutines gauge                                                                               \ngo_goroutines 29  ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "routines" } },
     "targets": [
      {
       "expr": "sum by (node) (\r\n   sum by(pod) (go_goroutines) \r\n   + on(pod) group_left(node) sum by(pod,node) (kube_pod_info{namespace=\"94-shared-services-kine\"})\r\n)",
       "legendFormat": "routines on {{pod}} on node {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "To remove",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kine requests latency per error ",
     "type": "timeseries",
     "description": " Length of time per SQL operation",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(kine_sql_time_seconds_bucket[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}