#!/bin/bash
# Builds kine for the HOST architecture and OS
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

if [ ${ARCH} = armv7l ] || [ ${ARCH} = arm ]; then
    export GOARCH="arm"
    export GOARM="7"
elif [ ${ARCH} = riscv64 ]; then
    export GOARCH="riscv64"
fi

if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/k3s-io/kine/pkg/version.Version=$VERSION"
LINKFLAGS="-X github.com/k3s-io/kine/pkg/version.GitCommit=$COMMIT $LINKFLAGS"

echo Building Kine
if [ "$CGO_ENABLED" = "0" ]; then 
    CGO_ENABLED=0 go build -ldflags "$LINKFLAGS" -tags nats -o bin/kine-nocgo
else
    CGO_CFLAGS="-DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_USE_ALLOCA=1" go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -tags nats -o bin/kine
fi