#!/bin/bash
# Builds kiune from multiple platforms and os
# Intended to be run within a buildx container that provides the --platform flag
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

export GOOS=${TARGETOS}
export GOARCH=${TARGETARCH}

if [ "$TARGETARCH" = "arm/v7" ]; then
    ARCH="-arm"
else
    ARCH="-${TARGETARCH}"
fi

# If not linux, add the os to the binary name
if [ "$TARGETOS" != "linux" ]; then
    OPT_OS="-${TARGETOS}"
fi

if [ "$TARGETOS" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/k3s-io/kine/pkg/version.Version=$VERSION"
LINKFLAGS="-X github.com/k3s-io/kine/pkg/version.GitCommit=$COMMIT $LINKFLAGS"

echo Building Mutliplaform Kine
CGO_CFLAGS="-DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_USE_ALLOCA=1" go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -tags nats -o bin/kine"${OPT_OS}${ARCH}"