#!/bin/bash
set -e

cd $(dirname $0)/..

. ./scripts/test-helpers

#echo Running go unit tests
go test -cover -tags=test ./...

# ---

docker ps

# ---

. ./scripts/test-run-sqlite
echo "Did test-run-sqlite $?"

. ./scripts/test-run-mysql
echo "Did test-run-mysql $?"

. ./scripts/test-run-postgres
echo "Did test-run-postgres $?"

. ./scripts/test-run-cockroachdb
echo "Did test-run-cockroachdb $?"

. ./scripts/test-run-nats
echo "did test-nats $?"

. ./scripts/test-run-nats-embedded
echo "did test-nats-embedded $?"

. ./scripts/test-run-nats-socket
echo "did test-nats-socket $?"

exit 0
