#!/bin/bash
set -e
cd $(dirname $0)/..

. ./scripts/version

TAG=${TAG:-${VERSION_TAG}${SUFFIX}}
IMAGE_NAME=${IMAGE_NAME:-kine}
IMAGE=${REPO}/${IMAGE_NAME}:${TAG}

test-setup
provision-database $DB_ARGS
start-test $@

echo "Running go unit tests"
local kine_url=$(cat $TEST_DIR/kine/*/metadata/url)
K3S_DATASTORE_ENDPOINT=$kine_url go test -v -cover -tags=test ./...

#echo "Running load tests"
#./scripts/test-load
