#!/bin/bash
set -e
cd $(dirname $0)/..

. ./scripts/version

TAG=${TAG:-${VERSION_TAG}${SUFFIX}}
IMAGE_NAME=${IMAGE_NAME:-kine}
IMAGE=${REPO}/${IMAGE_NAME}:${TAG}

test-setup
provision-database $DB_ARGS
start-test

for test_to_run in "$@"; do
    if [ ! -f "./scripts/$test_to_run" ]; then
        echo "test script not found: ./scripts/$test_to_run" >&2
        exit 1
    fi
    ./scripts/"$test_to_run"
done
