#!/bin/bash
start-test() {
    local ip=$(cat $TEST_DIR/databases/*/metadata/ip)
    local port=$(cat $TEST_DIR/databases/*/metadata/port)
    local pass=$(cat $TEST_DIR/databases/*/metadata/password)

    DB_CONNECTION_TEST="
        curl -d 
          '{\"statements\": [\"CREATE TABLE IF NOT EXISTS users (username)\", \"INSERT INTO users VALUES (\\\"alice\\\")\"]}' 
          $ip:$port" \
    timeout --foreground 1m bash -c "wait-for-db-connection"
    KINE_IMAGE=$IMAGE KINE_ENDPOINT="libsql://$ip:$port" provision-kine
    local kine_url=$(cat $TEST_DIR/kine/*/metadata/url)
    K3S_DATASTORE_ENDPOINT=$kine_url provision-cluster
}
export -f start-test

VERSION_LIST="\
    libsql-server v0.24.4"

while read ENGINE VERSION; do
    LABEL=$ENGINE-$VERSION DB_IMAGE=ghcr.io/tursodatabase/$ENGINE:$VERSION run-test
done <<< $VERSION_LIST
