#!/bin/bash

if [[ ! -v DIRTY ]]; then
  if [[ -n "$(git status --porcelain --untracked-files=no -z)" ]]; then
    DIRTY="-dirty"
  fi
fi

COMMIT="$(git rev-parse --short HEAD)"
GIT_TAG="${TAG:-$(git tag -l --contains HEAD | head -n 1)}"

if [[ -z "$DIRTY" ]] && [[ -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

GO=${GO-go}
ARCH=${ARCH:-$("${GO}" env GOARCH)}
SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
