#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [ -z "$DIRTY" ] && [ -n "$GIT_TAG" ]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -n "$ARCH" ]; then
    GOARCH=${ARCH}
fi
if [ -z "$GOARCH" ]; then
    GOARCH=$(go env GOHOSTARCH)
fi
if [ "$GOARCH" = "arm" ]; then
    GOARM=7
fi

ARCH="${GOARCH}"
SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
