name: Lint Action Workflows
on:
  pull_request:
    paths:
      - ".github/workflows/*"

jobs:
  acitonlint:
    name: Lint GitHub Workflows
    runs-on: ubuntu-latest # Runs on standard runner, docker pulls with --platform
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: actionlint
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2
        with:
          shellcheck: false
          pyflakes: false
          cache: false

