name: Release
on:
  release:
    types:
      - created

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
      TAG: ${{ github.ref_name }}
    permissions:
      contents: write # Needed to update release with binary assets
      packages: write # Needed for GHCR image push
      id-token: write # needed for the Vault authentication
      attestations: write # needed for attest action
      artifact-metadata: write # needed for attestation upload to GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Build binaries
        run: make multi-arch-build

      - name: Compute checksum for each binary
        run: |
          arch=("amd64" "arm64" "arm" "riscv64")
          cd dist/artifacts
          for a in "${arch[@]}"; do
            sha256sum kine-"${a}" > sha256sum-"${a}".txt
          done
          
      - name: Attest binaries
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4
        with:
          subject-path: dist/artifacts/kine-*

      - name: Upload binaries to release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: |
            dist/artifacts/kine-*
            dist/artifacts/*.txt

      - name: "Read Vault secrets"
        if: github.repository_owner == 'k3s-io'
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_TOKEN ;
    
      - name: Set DockerHub repo
        if: github.repository_owner != 'k3s-io'
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> "$GITHUB_ENV"

      - name: Login to DockerHub with Rancher Secrets
        if: github.repository_owner == 'k3s-io'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      # For forks, setup DockerHub login with GHA secrets
      - name: Login to DockerHub with GHA Secrets
        if: github.repository_owner != 'k3s-io'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        id: build
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          target: multi-arch-package
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/kine:latest
            ${{ env.DOCKER_USERNAME }}/kine:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/kine:latest
            ghcr.io/${{ github.repository_owner }}/kine:${{ github.ref_name }}
      
      - name: Attest images
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/kine
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
